CREATE TABLE submission_review (
	overall_rating TEXT NOT NULL, 
	relevance TEXT NOT NULL, 
	revision_possible TEXT NOT NULL, 
	paper_flavor TEXT NOT NULL, 
	summary TEXT NOT NULL, 
	strengths TEXT NOT NULL, 
	weaknesses TEXT NOT NULL, 
	novelty TEXT NOT NULL, 
	significance TEXT NOT NULL, 
	technical_depth TEXT NOT NULL, 
	experiments TEXT NOT NULL, 
	presentation TEXT NOT NULL, 
	details TEXT NOT NULL, 
	reproducibility TEXT NOT NULL, 
	revision_items TEXT NOT NULL, 
	confidence TEXT NOT NULL, 
	confidential_comments TEXT NOT NULL, 
	external_reviewer TEXT NOT NULL, 
	trainee_agreement TEXT NOT NULL, 
	submission_id INTEGER NOT NULL, 
	reviewer_id INTEGER NOT NULL, 
	PRIMARY KEY (submission_id, reviewer_id), 
	FOREIGN KEY(submission_id) REFERENCES submission (id), 
	FOREIGN KEY(reviewer_id) REFERENCES people (id)
)
